### ISSUE TITLE
Changed behaviour of GeomAPI_ExtremaCurveSurface in pythonocc 0.17

### ISSUE THREAD

**Issue by jnwalther** [tpaviot/pythonocc-core#308] opened 2016-09-23 08:19 UTC
Hi everyone,
I am using pythonocc to compute the intersection points between a B-spline surface  (Geom_BSplineSurface object) and a set of vectors (Geom_Line objects), using GeomAPI_ExtremaCurveSurface. This used to work like a charm in version 0.16.5, but after installing version 0.17.0 several intersections fail:
![failed_points](https://cloud.githubusercontent.com/assets/16652793/18778692/e370fea0-8175-11e6-8e0f-69beaea17282.png)
The number of failures seems to be somehow dependent on the length of the line evaluation interval [0,wmax]. Also, the surface's circumferential coordinate starts and ends at the top where the failures occur, so I don't know if this might have something to do with it. GeomAPI_IntCS manages to find the points, but is much slower than GeomAPI_ExtremaCurveSurface.

Have there been any changes in the function between versions which could explain this?

**Comment by tpaviot** [comment] 2016-09-23 09:03
@kngbuzzo Thank you for this feedback. pythonocc-0.17 is based upon oce-0.17.2, which contains many changes since the previous oce-0.16 (FYI this is the step from official OCCT671 to OCCT680). OCCT680 release notes (https://www.opencascade.com/sites/default/files/documents/Release_Notes_6.8.0.pdf) does not mention any change to the  Geom_ExtremaCurvedSurface function/algorithm, however there might have been many other changes to functions/classes used by  the Geom_ExtremaCurvedSurface class. Your use case seems to be complex, would it be possible that you provide a simple example that reproduces the issue ?

**Comment by tpaviot** [comment] 2016-09-23 09:21
@kngbuzzo Are you sure about the spelling of Geom_ExtremaCurvedSurface, I can't even fin such a class in pyocc-0.16 or 0.17

**Comment by kngbuzzo** [comment] 2016-09-23 09:40
@tpaviot Thanks for your answer. Geom_ExtremaCurvedSurface was a typo and should say Geom_ExtremaCurveSurface as in the title. Sorry about that. I have tried a second example, which is just a regular cylindrical barrel, and all the intersections work fine.

**Comment by tpaviot** [comment] 2016-09-23 09:49
@kngbuzzo It will be *very* difficult to debug without an example that show the error. There might have some parameters to tune, but unfortunately I don't use to work with this class and can't be helpfull.

**Comment by kngbuzzo** [comment] 2016-09-23 11:44
@tpaviot I'm sorry I don't have a good example to share. The algorithm seems to work great with all my simpler models... Btw. I went through the release notes and they mention new global optimization algorithms for extrema computation in their highlights. More specifically, the Extrema_GenExtCS class is said to have been changed, which, I suspect, is somehow being used by GeomAPI_ExtremaCurveSurface. In a way this makes sense, because the more I think about it I am certain that my problem is related to the initial guess for the optimization, which is what has been changed, from my understanding. So I guess that answers at least part of my original question.

**Comment by jf---** [comment] 2016-10-29 14:57
@kngbuzzo , we appreciate your feedback, but lets have an example, or close this issue; its not in an actionable state... 

without being able to reproduce the issue, this will take too much resources on our end I'm afraid...

**Comment by kngbuzzo** [comment] 2016-11-02 16:00
@jf--- thanks for bringing this back up and sorry for the delay. I came up with an example to illustrate my problem based on an ellipsoid, which you can find here: https://github.com/kngbuzzo/pythonocc_examples For 2500 intersections I get the following output:
pythonocc 0.16.5:
```
Time for intersections 0.480000019073
[]
0 failures
```
![figure_1-0](https://cloud.githubusercontent.com/assets/16652793/19936488/d4e630d6-a11d-11e6-88d6-698deb9fc539.png)

pythonocc 0.17:
```
Time for intersections 2.21000003815
[[  2.00000000e-01   3.00321910e-04   0.00000000e+00]
 [  1.15714286e+01   3.79488064e-01   4.89295676e-02]
    ...
 [  5.21836735e+01   4.00839802e-01  -5.16825693e-02]
 [  2.00000000e-01   3.00321910e-04  -7.35576530e-20]]
107 failures
```
![figure_1-1](https://cloud.githubusercontent.com/assets/16652793/19936124/c24a1196-a11c-11e6-861d-f33d1df3bc24.png)

The black dots indicate failures (obviously). I hope this is a little more useful to you.

**Comment by jf---** [comment] 2016-11-02 16:25
that's perfect @kngbuzzo , thanks so much! 
Can you share the script please, than I can delve deeper into this, whether this can be overcome in pythonocc or should be escalated to OpenCascade. 

Perhaps you can share it as at gist.github.com, or just paste it here if you like...

Thanks a lot for this!

**Comment by kngbuzzo** [comment] 2016-11-02 17:52
@jf--- , I added the script in a repository under my name, the link to which I have provided above (<https://github.com/kngbuzzo/pythonocc_examples>). Is that ok for you?

**Comment by jf---** [comment] 2016-11-02 17:55
Shoot, I misread your earlier comment, sorry @kngbuzzo & thanks again!!

**Comment by kngbuzzo** [comment] 2016-11-03 08:33
Cool, thanks for loking into it @jf--- !

**Comment by rainman110** [comment] 2017-02-01 10:53
@kngbuzzo  I think this issue should be posted directly at the [OCCT Mantis](https://tracker.dev.opencascade.org/my_view_page.php)? Did you already do it?

We could provide an even more simplified example
 - one, where the computation time is much slower than before
 - one, where the intersection is failing

**Comment by kngbuzzo** [comment] 2017-02-13 14:22
@rainman110 No, I haven't posted anything yet. Will they be able to work with the example in Python?

Following your suggestions, I have added two more test cases to the example script.

**Comment by rainman110** [comment] 2017-02-13 18:04
@kngbuzzo We should create a minimalistic  C++ example for the OCCT guys. I could provide help, if you want. Great with the new test cases!

**Comment by kngbuzzo** [comment] 2017-02-14 15:27
@rainman110 If you could give me a hand with that, that'd be great.

**Comment by tpaviot** [comment] 2020-01-05 07:52
@kngbuzzo What's up with this issue. Did you try your code with more recent pythonocc release ?

**Comment by kngbuzzo** [comment] 2020-02-05 12:18
@tpaviot I ran the updated version of the code using versions 0.18.2 and 7.4.0-rc1 to these results:


![result_0 18 2](https://user-images.githubusercontent.com/16652793/73841015-ddc0be00-4819-11ea-8aa9-8d1f496bab6e.png)
![result_7 4 0-rc1](https://user-images.githubusercontent.com/16652793/73840877-8b7f9d00-4819-11ea-8745-4bde1a8bef83.png)

OCC 7 is clearly improving the situation (possibly at the cost of performance), but the fundamental issue remains.

**Comment by jf---** [comment] 2020-02-17 12:50
@jnwalther is it feasible that the failing samples ( impressive plot btw ) are an [Umbilical point](https://en.wikipedia.org/wiki/Umbilical_point)?

**Comment by jnwalther** [comment] 2020-05-12 07:51
@jf--- I went ahead and checked my example surface for umbilical points. The source data is an ellipsoid with a circular cross section (i.e. b==c), which means it should only have an umbilical point at the tip. I compared the principal curvature distibutions for an analytical ellipsoid to my test surface, which brought to light some problems wrt the continuity. After fixing this, I get the plot below, which suggests that the B-Spline surface accurately represents the location of the umbilical points (Coloring is W as definied by [Maekawa et al.](https://doi.org/10.1016/0167-8396(95)00018-6); the criterion for an umbilical point is W==0).

![ellipse_model_updated](https://user-images.githubusercontent.com/16652793/81654620-f9012200-9435-11ea-83bc-bda4a39fe064.jpeg)

Fixing the surface also brought down the number of failures further to
- OCC6: 72
- OCC7: 13

However, I have to report, that while the failures occur more often close the umbilical points, they do not occur there exclusively, as shown in the figure below.
![ellipse_model_failures_occ7](https://user-images.githubusercontent.com/16652793/81652579-3fee1800-9434-11ea-87b5-aff3e40aa753.jpeg)

**Comment by rainman110** [comment] 2020-05-12 09:32
@jnwalther I forgot to follow up this. Let’s simply post this issue at the official occt bug tracker. PythonOCC can’t fix this issue unfortunately.
Could you extract the failing points, or even better, write a python test script comparing with the expected values? I’ll translate this then into c++

**Comment by jnwalther** [comment] 2020-05-12 12:30
@rainman110 I agree we should take this issue upsteam. If you could help me out with the C++ part, that'd be great. As requested, I put together a minimal version of the test here: https://github.com/jnwalther/pythonocc_examples/blob/master/test_minimal.py
Let me know if you can work with this or if you need anything else.

**Comment by rainman110** [comment] 2020-05-12 12:55
@jnwalther Could you add to your script also the expected values? This could lead to an even much better test checking not only failure, but also accuracy.

**Comment by jnwalther** [comment] 2020-05-12 12:57
@rainman110 By expected values you mean uvw?

**Comment by rainman110** [comment] 2020-05-12 13:03
Either this or the xyz coordinates

**Comment by jnwalther** [comment] 2020-05-12 13:05
Ah, but the xyz coordinates are already there: https://github.com/jnwalther/pythonocc_examples/blob/master/expected_points.csv
The file is referred to in the script.

**Comment by rainman110** [comment] 2020-05-12 13:07
Ah okay... I thought, the epected point could be derived from the ellipse equation, but this list is probably also okay.

**Comment by jnwalther** [comment] 2020-05-12 13:12
Ah ok, I understand. Maybe using the list not so bad though. Otherwise we'd have to consider how well the example surface approximates an actual ellipsoid.

**Comment by tpaviot** [comment] 2024-05-23 07:17
Old issue, please reopen if still valid with latest release

**Closed by tpaviot** 2024-05-23 07:17 UTC
Labels: bug
